### ISSUE TITLE
Bug: 1.0.2 版本没有编译

### ISSUE THREAD

**Issue by windbullet** [Vincent-the-gamer/koishi-plugin-gemini-pro#1]
![image](https://github.com/Vincent-the-gamer/koishi-plugin-gemini-pro/assets/47932422/e9f376c5-a4d7-4929-8de6-cdf035f6cbf9)
应该是因为 tsconfig.json 缺失 emitDeclarationOnly: true 导致的

**Comment by Vincent-the-gamer** [comment]
> ![image](https://private-user-images.githubusercontent.com/47932422/345009232-e9f376c5-a4d7-4929-8de6-cdf035f6cbf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NjkyODMsIm5iZiI6MTcxOTk2ODk4MywicGF0aCI6Ii80NzkzMjQyMi8zNDUwMDkyMzItZTlmMzc2YzUtYTRkNy00OTI5LThkZTYtY2RmMDM1ZjZjYmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDAxMDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1OTFlYTgyYjY4MTk4MTdlYTFmNjcxZjI1M2I4Y2U5Y2E4NGNmMzFjNjA1OTEyNTdjMjkzNzEyODM3YzU1NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5z62dbx-PhYWXbb_Lit_34CtHv_pkt85YbafSmRKBaY) 应该是因为 tsconfig.json 缺失 emitDeclarationOnly: true 导致的

发现了，yakumo build没有生成index.js, emitDeclarationOnly: true加上也没有，我再看看是哪的问题（233

**Comment by Vincent-the-gamer** [comment]
找到原因了，貌似是依赖缺失导致的

```
esbuild: plugins/gemini-pro/src/index.tsx -> plugins/gemini-pro/lib/index.js
../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:27: error: Missing dependency: @satorijs/element (此处省略本地路径)
```

具体解决办法再看

**Comment by Vincent-the-gamer** [comment]
鉴定完毕，是tsconfig导致的，因为我使用了tsx，但是在现有的tsconfig配置情况下，加上emitDeclarationOnly: true时，在yakumo build时，会提示找不到@satorijs/element依赖，而此依赖不应该由开发者管理，现有的解决办法是使用之前的tsconfig配置来构建，或是将代码中tsx改为h函数。 现采用后者来修复问题。

**Comment by Vincent-the-gamer** [comment]
目前已经正确编译并且发布了
